services:
  hallo_verden_voter.security:
    class: HalloVerden\VoterBundle\Security\Security
    arguments:
      $security: '@security.helper'
      $accessDecisionManager: '@security.access.decision_manager'

  HalloVerden\VoterBundle\Security\SecurityInterface: '@hallo_verden_voter.security'

  hallo_verden_voter.oauth_authorization_voter:
    class: HalloVerden\VoterBundle\Security\Voter\OauthAuthorizationVoter
    arguments:
      $security: '@hallo_verden_voter.security'
    tags:
      - { name: security.voter }

  hallo_verden_voter.authentication_voter:
    class: HalloVerden\VoterBundle\Security\Voter\AuthenticationVoter
    tags:
      - { name: security.voter }

  hallo_verden_voter.set_authenticator_on_login_listener:
    class: HalloVerden\VoterBundle\EventListener\SetAuthenticatorOnLoginListener
    tags:
      - { name: kernel.event_subscriber }

  hallo_verden_voter.endpoint_scope_voter:
    class: HalloVerden\VoterBundle\Security\Voter\EndpointScopeVoter
    arguments:
      $security: '@hallo_verden_voter.security'
      $requestStack: '@request_stack'
    tags:
      - { name: security.voter }
