services:
  hallo_verden_voter.security:
    class: HalloVerden\VoterBundle\Security\Security
    arguments:
      $security: '@security.helper'
      $accessDecisionManager: '@security.access.decision_manager'

  HalloVerden\VoterBundle\Security\SecurityInterface: '@hallo_verden_voter.security'

  hallo_verden_voter.oauth_authorization_voter:
    parent: hallo_verden_voter.voter
    class: HalloVerden\VoterBundle\Security\Voter\OauthAuthorizationVoter
    tags:
      - { name: security.voter }

  hallo_verden_voter.authentication_voter:
    parent: hallo_verden_voter.voter
    class: HalloVerden\VoterBundle\Security\Voter\AuthenticationVoter
    tags:
      - { name: security.voter }

  hallo_verden_voter.set_authenticator_on_login_listener:
    class: HalloVerden\VoterBundle\EventListener\SetAuthenticatorOnLoginListener
    tags:
      - { name: kernel.event_subscriber }

  hallo_verden_voter.route_info_service:
    class: HalloVerden\VoterBundle\Route\RouteInfoService
    arguments:
      $router: '@router.default'
      $cache: '@cache.system'

  hallo_verden_voter.route_info_cache_warmer:
    class: HalloVerden\VoterBundle\Cache\RouteInfoCacheWarmer
    arguments:
      $routeInfoService: '@hallo_verden_voter.route_info_service'
    tags:
      - { name: kernel.cache_warmer }

  hallo_verden_voter.endpoint_scope_voter:
    class: HalloVerden\VoterBundle\Security\Voter\EndpointScopeVoter
    parent: hallo_verden_voter.voter
    arguments:
      $requestStack: '@request_stack'
      $routeInfoService: '@hallo_verden_voter.route_info_service'
    tags:
      - { name: security.voter }

  hallo_verden_voter.voter:
    abstract: true
    class: HalloVerden\VoterBundle\Security\Voter\Voter
    arguments:
      $security: '@security.helper'
      $accessDecisionManager: '@security.access.decision_manager'
